### ISSUE TITLE
Hello author, when will you release the source code?

### ISSUE THREAD

**Issue by 2311762665** [yanx27/2DPASS#1]
Hello author, I am so interested in your research content. When will you release the source code?

**Comment by yanx27** [comment]
Hi @2311762665, thanks for your attention. We are organizing the codebase and will release it around the ECCV conference.

**Comment by JulesSanchez** [comment]
Hello, will the pre-trained weights for semanticKITTI and nuScenes be released alongside the codebase ?

Thank you for your work
