### ISSUE TITLE
About xModalKD code and MSFSKD figure

### ISSUE THREAD

**Issue by LavenderLA** [yanx27/2DPASS#12]
Hi, thanks for your excellent work!

I notice that in Fig.4 of 2DPASS paper, the enhanced 3D features is the summation of 3D features and output from the 2D Learner. However,  in this [Line](https://github.com/yanx27/2DPASS/blob/eb649c3eeb193fad95421f3f986a217c6df2d983/network/arch_2dpass.py#L96) of the code, 3D features from `spvcnn.py` is directly feed into the 3D classifier, without adding `feat_learner`. What's more, this forward path is not processed during inference, which is also not consistent with the solid line in Fig 4. 

Would you please kindly explain the difference between code and paper, and which variable in your code is corresponding to the **Enhanced 3D Features** in Fig.4? Thanks so much!

**Comment by yanx27** [comment]
Hi @LavenderLA this issue seems to be the same as https://github.com/yanx27/2DPASS/issues/3, and  the input for the 2D learner is not utilized in the inference phase. We already update our arXiv, please check the new one.
