### ISSUE TITLE
Could you teach me how to draw the color on the objects by vis_utils.py

### ISSUE THREAD

**Issue by hellohaozheng** [yanx27/2DPASS#14]
Thank you a lot for your impressing work! Could you teach me how to draw the color on the objects by vis_utils.py? if possible, update a demo for visualization.

**Comment by yanx27** [comment]
Hi @hellohaozheng , an naive way, you can use the below codes [here](https://github.com/yanx27/2DPASS/blob/eb649c3eeb193fad95421f3f986a217c6df2d983/dataloader/dataset.py#L152).
```
from utils.vis_utils import draw_points_image_labels
draw_points_image_labels(
np.array(image),
points_img.astype(int),
labels[keep_idx],
color_palette_type='SemanticKITTI_long'
)
```

**Comment by hellohaozheng** [comment]
Thanks a lot!
