### ISSUE TITLE
A question about the dataloader

### ISSUE THREAD

**Issue by ch2718n** [yanx27/2DPASS#17]
Thanks for your excellent work ! I have a small question about the dataloader. The length of the img_indices、img_label and point2img_index may be different for each frame of data. How to put them into the same batch ?

**Comment by yanx27** [comment]
@ch2718n Hi, see [this function](https://github.com/yanx27/2DPASS/blob/733f1ce0b1fa576ea7a1607b116c4914d3bcaed4/dataloader/dataset.py#L460).

**Comment by ch2718n** [comment]
Oh, i get it ! Thank you for your quick reply.
