### ISSUE TITLE
论文请教

### ISSUE THREAD

**Issue by lmomoy** [yanx27/2DPASS#2]
作者你好，很感谢产出这么优秀的工作，在阅读论文后我有一些疑惑请教。

在MSFSKD模块中，我所理解上面一条支路输出的是2D分割结果，下面一条支路是3D分割结果，请问这两种空间的输出如何计算KL散度呢
![image](https://user-images.githubusercontent.com/49771303/181243250-c113c760-bfe7-4182-8998-1ea8421b75ef.png)

**Comment by yanx27** [comment]
Hi @lmomoy ,please refer to Section 3.3 about how to gain point-to-pixel correspondence.
