### ISSUE TITLE
the question about "coors_inv_last" in 2DPASS/spvnn.py

### ISSUE THREAD

**Issue by xiaxiangteng** [yanx27/2DPASS#22]
Thank you for your great work! But I have a small question. In 2DPASS/spvnn.py, I think you use "coors_inv_last" to devoxelization in the line 92, so in 2DPASS/arch_2dpass.py/xModalKD.forward(), should voxelize it with "coors_inv_last" in the line 101?

**Comment by isunLt** [comment]
> Thank you for your great work! But I have a small question. In 2DPASS/spvnn.py, I think you use "coors_inv_last" to devoxelization in the line 92, so in 2DPASS/arch_2dpass.py/xModalKD.forward(), should voxelize it with "coors_inv_last" in the line 101?

Hi! Have you try to solve the problem and did the performance improved? I have the same question with you and I modify the code to use `coors_inv_last` to devoxelization `pts_pred_full`. The code is shown as follow:
```python
        for idx, scale in enumerate(self.pooling_scale):
            img_feat = data_dict['img_scale{}'.format(idx)]  # img_scale0 correspond to img_scale2 in the original code and so on
            pts_feat = data_dict['layer_{}'.format(idx)]['pts_feat']
            coors_inv = data_dict['scale_{}'.format(scale)]['coors_inv']

            # 3D prediction
            pts_pred_full = self.multihead_3d_classifier[idx](pts_feat)

            # correspondence
            pts_label_full = self.voxelize_labels(data_dict['labels'], data_dict['layer_{}'.format(idx)]['full_coors'])
            pts_feat = self.p2img_mapping(pts_feat[coors_inv], point2img_index, batch_idx)
            pts_pred = self.p2img_mapping(pts_pred_full[coors_inv], point2img_index, batch_idx)
```
where `self.pooling_scale=[1,2,4,8]` but finally get a result of 65.288 at mIoU on SemanticKITTI, which is 0.6 lower than original code.

**Comment by xiaxiangteng** [comment]
> > Thank you for your great work! But I have a small question. In 2DPASS/spvnn.py, I think you use "coors_inv_last" to devoxelization in the line 92, so in 2DPASS/arch_2dpass.py/xModalKD.forward(), should voxelize it with "coors_inv_last" in the line 101?
> 
> Hi! Have you try to solve the problem and did the performance improved? I have the same question with you and I modify the code to use `coors_inv_last` to devoxelization `pts_pred_full`. The code is shown as follow:
> 
> ```python
>         for idx, scale in enumerate(self.pooling_scale):
>             img_feat = data_dict['img_scale{}'.format(idx)]  # img_scale0 correspond to img_scale2 in the original code and so on
>             pts_feat = data_dict['layer_{}'.format(idx)]['pts_feat']
>             coors_inv = data_dict['scale_{}'.format(scale)]['coors_inv']
> 
>             # 3D prediction
>             pts_pred_full = self.multihead_3d_classifier[idx](pts_feat)
> 
>             # correspondence
>             pts_label_full = self.voxelize_labels(data_dict['labels'], data_dict['layer_{}'.format(idx)]['full_coors'])
>             pts_feat = self.p2img_mapping(pts_feat[coors_inv], point2img_index, batch_idx)
>             pts_pred = self.p2img_mapping(pts_pred_full[coors_inv], point2img_index, batch_idx)
> ```
> 
> where `self.pooling_scale=[1,2,4,8]` but finally get a result of 65.288 at mIoU on SemanticKITTI, which is 0.6 lower than original code.

I made a similar change to you, and it didn't improve

**Comment by xiaxiangteng** [comment]
> > Thank you for your great work! But I have a small question. In 2DPASS/spvnn.py, I think you use "coors_inv_last" to devoxelization in the line 92, so in 2DPASS/arch_2dpass.py/xModalKD.forward(), should voxelize it with "coors_inv_last" in the line 101?
> 
> Hi! Have you try to solve the problem and did the performance improved? I have the same question with you and I modify the code to use `coors_inv_last` to devoxelization `pts_pred_full`. The code is shown as follow:
> 
> ```python
>         for idx, scale in enumerate(self.pooling_scale):
>             img_feat = data_dict['img_scale{}'.format(idx)]  # img_scale0 correspond to img_scale2 in the original code and so on
>             pts_feat = data_dict['layer_{}'.format(idx)]['pts_feat']
>             coors_inv = data_dict['scale_{}'.format(scale)]['coors_inv']
> 
>             # 3D prediction
>             pts_pred_full = self.multihead_3d_classifier[idx](pts_feat)
> 
>             # correspondence
>             pts_label_full = self.voxelize_labels(data_dict['labels'], data_dict['layer_{}'.format(idx)]['full_coors'])
>             pts_feat = self.p2img_mapping(pts_feat[coors_inv], point2img_index, batch_idx)
>             pts_pred = self.p2img_mapping(pts_pred_full[coors_inv], point2img_index, batch_idx)
> ```
> 
> where `self.pooling_scale=[1,2,4,8]` but finally get a result of 65.288 at mIoU on SemanticKITTI, which is 0.6 lower than original code.

I made a similar change to you, and it didn't improve too._
for idx, scale in enumerate(self.scale_list):
            img_feat = data_dict['img_scale{}'.format(scale)]
            pts_feat = data_dict['layer_{}'.format(idx)]['pts_feat']
            scale_last = self.scale_list[idx-1] if idx != 0 else 1
            coors_inv = data_dict['scale_{}'.format(scale_last)]['coors_inv']

**Comment by xiaxiangteng** [comment]
> > Thank you for your great work! But I have a small question. In 2DPASS/spvnn.py, I think you use "coors_inv_last" to devoxelization in the line 92, so in 2DPASS/arch_2dpass.py/xModalKD.forward(), should voxelize it with "coors_inv_last" in the line 101?
> 
> Hi! Have you try to solve the problem and did the performance improved? I have the same question with you and I modify the code to use `coors_inv_last` to devoxelization `pts_pred_full`. The code is shown as follow:
> 
> ```python
>         for idx, scale in enumerate(self.pooling_scale):
>             img_feat = data_dict['img_scale{}'.format(idx)]  # img_scale0 correspond to img_scale2 in the original code and so on
>             pts_feat = data_dict['layer_{}'.format(idx)]['pts_feat']
>             coors_inv = data_dict['scale_{}'.format(scale)]['coors_inv']
> 
>             # 3D prediction
>             pts_pred_full = self.multihead_3d_classifier[idx](pts_feat)
> 
>             # correspondence
>             pts_label_full = self.voxelize_labels(data_dict['labels'], data_dict['layer_{}'.format(idx)]['full_coors'])
>             pts_feat = self.p2img_mapping(pts_feat[coors_inv], point2img_index, batch_idx)
>             pts_pred = self.p2img_mapping(pts_pred_full[coors_inv], point2img_index, batch_idx)
> ```
> 
> where `self.pooling_scale=[1,2,4,8]` but finally get a result of 65.288 at mIoU on SemanticKITTI, which is 0.6 lower than original code.
I made a similar change to you, and it didn't improve too._
`for idx, scale in enumerate(self.scale_list):
    img_feat = data_dict['img_scale{}'.format(scale)]
    pts_feat = data_dict['layer_{}'.format(idx)]['pts_feat']
    scale_last = self.scale_list[idx-1] if idx != 0 else 1
    coors_inv = data_dict['scale_{}'.format(scale_last)]['coors_inv']`

**Comment by xiaxiangteng** [comment]
> > Thank you for your great work! But I have a small question. In 2DPASS/spvnn.py, I think you use "coors_inv_last" to devoxelization in the line 92, so in 2DPASS/arch_2dpass.py/xModalKD.forward(), should voxelize it with "coors_inv_last" in the line 101?
> 
> Hi! Have you try to solve the problem and did the performance improved? I have the same question with you and I modify the code to use `coors_inv_last` to devoxelization `pts_pred_full`. The code is shown as follow:
> 
> ```python
>         for idx, scale in enumerate(self.pooling_scale):
>             img_feat = data_dict['img_scale{}'.format(idx)]  # img_scale0 correspond to img_scale2 in the original code and so on
>             pts_feat = data_dict['layer_{}'.format(idx)]['pts_feat']
>             coors_inv = data_dict['scale_{}'.format(scale)]['coors_inv']
> 
>             # 3D prediction
>             pts_pred_full = self.multihead_3d_classifier[idx](pts_feat)
> 
>             # correspondence
>             pts_label_full = self.voxelize_labels(data_dict['labels'], data_dict['layer_{}'.format(idx)]['full_coors'])
>             pts_feat = self.p2img_mapping(pts_feat[coors_inv], point2img_index, batch_idx)
>             pts_pred = self.p2img_mapping(pts_pred_full[coors_inv], point2img_index, batch_idx)
> ```
> 
> where `self.pooling_scale=[1,2,4,8]` but finally get a result of 65.288 at mIoU on SemanticKITTI, which is 0.6 lower than original code.

I made a similar change to you, and it didn't improve too.
for idx, scale in enumerate(self.scale_list): 
        img_feat = data_dict['img_scale{}'.format(scale)] 
        pts_feat = data_dict['layer_{}'.format(idx)]['pts_feat'] 
        scale_last = self.scale_list[idx-1] if idx != 0 else 1 
        coors_inv = data_dict['scale_{}'.format(scale_last)]['coors_inv']

**Comment by isunLt** [comment]
> > > Thank you for your great work! But I have a small question. In 2DPASS/spvnn.py, I think you use "coors_inv_last" to devoxelization in the line 92, so in 2DPASS/arch_2dpass.py/xModalKD.forward(), should voxelize it with "coors_inv_last" in the line 101?
> > 
> > 
> > Hi! Have you try to solve the problem and did the performance improved? I have the same question with you and I modify the code to use `coors_inv_last` to devoxelization `pts_pred_full`. The code is shown as follow:
> > ```python
> >         for idx, scale in enumerate(self.pooling_scale):
> >             img_feat = data_dict['img_scale{}'.format(idx)]  # img_scale0 correspond to img_scale2 in the original code and so on
> >             pts_feat = data_dict['layer_{}'.format(idx)]['pts_feat']
> >             coors_inv = data_dict['scale_{}'.format(scale)]['coors_inv']
> > 
> >             # 3D prediction
> >             pts_pred_full = self.multihead_3d_classifier[idx](pts_feat)
> > 
> >             # correspondence
> >             pts_label_full = self.voxelize_labels(data_dict['labels'], data_dict['layer_{}'.format(idx)]['full_coors'])
> >             pts_feat = self.p2img_mapping(pts_feat[coors_inv], point2img_index, batch_idx)
> >             pts_pred = self.p2img_mapping(pts_pred_full[coors_inv], point2img_index, batch_idx)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > where `self.pooling_scale=[1,2,4,8]` but finally get a result of 65.288 at mIoU on SemanticKITTI, which is 0.6 lower than original code.
> 
> I made a similar change to you, and it didn't improve too. for idx, scale in enumerate(self.scale_list): img_feat = data_dict['img_scale{}'.format(scale)] pts_feat = data_dict['layer_{}'.format(idx)]['pts_feat'] scale_last = self.scale_list[idx-1] if idx != 0 else 1 coors_inv = data_dict['scale_{}'.format(scale_last)]['coors_inv']

Thanks for your reply! It's somewhat strange.

**Comment by wayazg** [comment]
> 

Hi! I also found this problem. But I think it is not enough to just change here. Another place should also be changed.
"network/spvcnn.py" in the line 126, should be changed to
`self.strides = [int(scale) for scale in self.scale_list]`

**Comment by isunLt** [comment]
> > 
> 
> Hi! I also found this problem. But I think it is not enough to just change here. Another place should also be changed. "network/spvcnn.py" in the line 126, should be changed to `self.strides = [int(scale) for scale in self.scale_list]`

I think you are right. Do you get any positive results after change this line?

**Comment by wayazg** [comment]
> > > 
> > 
> > 
> > Hi! I also found this problem. But I think it is not enough to just change here. Another place should also be changed. "network/spvcnn.py" in the line 126, should be changed to `self.strides = [int(scale) for scale in self.scale_list]`
> 
> I think you are right. Do you get any positive results after change this line?

Thank you for your quick reply! I haven't done the experiment yet. I may do it soon.

**Comment by isunLt** [comment]
> > > > 
> > > 
> > > 
> > > Hi! I also found this problem. But I think it is not enough to just change here. Another place should also be changed. "network/spvcnn.py" in the line 126, should be changed to `self.strides = [int(scale) for scale in self.scale_list]`
> > 
> > 
> > I think you are right. Do you get any positive results after change this line?
> 
> Thank you for your quick reply! I haven't done the experiment yet. I may do it soon.

I see. Thanks for your sharing!

**Comment by isunLt** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > Hi! I also found this problem. But I think it is not enough to just change here. Another place should also be changed. "network/spvcnn.py" in the line 126, should be changed to `self.strides = [int(scale) for scale in self.scale_list]`
> > > > 
> > > > 
> > > > I think you are right. Do you get any positive results after change this line?
> > > 
> > > 
> > > Thank you for your quick reply! I haven't done the experiment yet. I may do it soon.
> > 
> > 
> > I see. Thanks for your sharing!
> 
> I have changed the above two places. As a result of the experiment, miou decreased by about 1%. This is strange!

I am doing this experiment, too. Which dataset do you train the network on? I got 0.6% mIoU decrease on semanticKITTI but 0.1% mIoU increase on nuScenes when only change the line in `xModalKD`.

**Comment by wayazg** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > Hi! I also found this problem. But I think it is not enough to just change here. Another place should also be changed. "network/spvcnn.py" in the line 126, should be changed to `self.strides = [int(scale) for scale in self.scale_list]`
> > > > > 
> > > > > 
> > > > > I think you are right. Do you get any positive results after change this line?
> > > > 
> > > > 
> > > > Thank you for your quick reply! I haven't done the experiment yet. I may do it soon.
> > > 
> > > 
> > > I see. Thanks for your sharing!
> > 
> > 
> > I have changed the above two places. As a result of the experiment, miou decreased by about 1%. This is strange!
> 
> I am doing this experiment, too. Which dataset do you train the network on? I got 0.6% mIoU decrease on semanticKITTI but 0.1% mIoU increase on nuScenes when only change the line in `xModalKD`.

I did this experiment on the semanticKITTI dataset. Judging from the results recorded by the tensorboard, I suspect that the change in indicators may be caused by randomness.🤣

**Comment by xiaxiangteng** [comment]
> > 
> 
> Hi! I also found this problem. But I think it is not enough to just change here. Another place should also be changed. "network/spvcnn.py" in the line 126, should be changed to `self.strides = [int(scale) for scale in self.scale_list]`

wow, I think this is a big problem because it affects the backbone of the network ---- SparseCNN. It resulted in a mismatch between indices and spatial_shape in the SpaeseConvTensor in 2DPASS/spvnn.py lines 101 through 106

**Comment by yanx27** [comment]
Hi, sorry for the late response.  After checking the original codes of paper submission, I find out that the error occurs when we reorganize the codebase. In the original codes, `spvcnn.py` and `arch_2dpass.py` are in the same function, which is messy to read them. This error does not affect the results in the paper, but it is also strange to me that the misaligned features still improve the performance of baseline. I will re-train the codes this week and give feedbacks. Sorry for the bug and inconvenience again.

**Comment by isunLt** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > Hi! I also found this problem. But I think it is not enough to just change here. Another place should also be changed. "network/spvcnn.py" in the line 126, should be changed to `self.strides = [int(scale) for scale in self.scale_list]`
> > > > > > 
> > > > > > 
> > > > > > I think you are right. Do you get any positive results after change this line?
> > > > > 
> > > > > 
> > > > > Thank you for your quick reply! I haven't done the experiment yet. I may do it soon.
> > > > 
> > > > 
> > > > I see. Thanks for your sharing!
> > > 
> > > 
> > > I have changed the above two places. As a result of the experiment, miou decreased by about 1%. This is strange!
> > 
> > 
> > I am doing this experiment, too. Which dataset do you train the network on? I got 0.6% mIoU decrease on semanticKITTI but 0.1% mIoU increase on nuScenes when only change the line in `xModalKD`.
> 
> I did this experiment on the semanticKITTI dataset. Judging from the results recorded by the tensorboard, I suspect that the change in miou may be caused by the randomness.🤣

Hi, my experiment is done. It grow from 65.3@mIoU to 65.9@mIoU and keep the same performance as the original github version.

**Comment by rogercomeon** [comment]
> Thank you for your great work! But I have a small question. In 2DPASS/spvnn.py, I think you use "coors_inv_last" to devoxelization in the line 92, so in 2DPASS/arch_2dpass.py/xModalKD.forward(), should voxelize it with "coors_inv_last" in the line 101?

hello,I would like to ask why coors_inv_last here does not perform feature aggregation on the voxel of the previous scale based on the index of the current voxel but devoxelization. This question has been bugging me for days, I would be very grateful if I could get your answer.
```
  v_fea_inv = torch_scatter.scatter_mean(v_fea.features[coors_inv_last], coors_inv, dim=0)
```

**Comment by rogercomeon** [comment]
> > > > > > > > > 
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Hi! I also found this problem. But I think it is not enough to just change here. Another place should also be changed. "network/spvcnn.py" in the line 126, should be changed to `self.strides = [int(scale) for scale in self.scale_list]`
> > > > > > > 
> > > > > > > 
> > > > > > > I think you are right. Do you get any positive results after change this line?
> > > > > > 
> > > > > > 
> > > > > > Thank you for your quick reply! I haven't done the experiment yet. I may do it soon.
> > > > > 
> > > > > 
> > > > > I see. Thanks for your sharing!
> > > > 
> > > > 
> > > > I have changed the above two places. As a result of the experiment, miou decreased by about 1%. This is strange!
> > > 
> > > 
> > > I am doing this experiment, too. Which dataset do you train the network on? I got 0.6% mIoU decrease on semanticKITTI but 0.1% mIoU increase on nuScenes when only change the line in `xModalKD`.
> > 
> > 
> > I did this experiment on the semanticKITTI dataset. Judging from the results recorded by the tensorboard, I suspect that the change in miou may be caused by the randomness.🤣
> 
> Hi, my experiment is done. It grow from 65.3@mIoU to 65.9@mIoU and keep the same performance as the original github version.

hello,I would like to ask why coors_inv_last here does not perform feature aggregation on the voxel of the previous scale based on the index of the current voxel but devoxelization. This question has been bugging me for days, I would be very grateful if I could get your answer.
```
  v_fea_inv = torch_scatter.scatter_mean(v_fea.features[coors_inv_last], coors_inv, dim=0)
```
