### ISSUE TITLE
training error about KeyError: 'Tr'

### ISSUE THREAD

**Issue by wyw-dlut** [yanx27/2DPASS#23]
Thanks for sharing your excellent work. When i trianed the model,  i met the error: './2DPASS-main/dataloader/pc_dataset.py", line 94, in read_calib    calib_out['Tr'][:3, :4] = calib_all['Tr'].reshape(3, 4)'. how could i solve this problem.

**Comment by bersecke** [comment]
Make sure your calibration txt files include the "Tr" line. You can download them here: http://www.cvlibs.net/download.php?file=data_odometry_calib.zip

**Comment by vijayM12** [comment]
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    from dataloader.dataset import get_model_class, get_collate_class
  File "/content/drive/MyDrive/2DPASS-main/dataloader/dataset.py", line 11, in <module>
    from nuscenes.utils.geometry_utils import view_points
ModuleNotFoundError: No module named 'nuscenes'

Hello, I am getting this error while i am trying to do the repo of 2Dpass and run the testing code given . Please help

**Comment by wyw-dlut** [comment]
thx for ur help. it works
