### ISSUE TITLE
about pictures problem

### ISSUE THREAD

**Issue by cama36** [yanx27/2DPASS#29]
hello,thank you for your great work! why i unable to test pretrained model with no pictures?

**Comment by cama36** [comment]
I saw in the paper that 2d pictures of network design are only used in training, and good results can be obtained without using 2d pictures in testing. However, I found that the test still needs to load pictures. Did I do anything wrong? Thank you very much

**Comment by Montyro** [comment]
Thats just how the dataloader is programmed, if you don't have the pictures downloaded, it will still search for them and return errors. I created a fork that makes the dataloader ignore the 2D information when using --baseline only. It works for training, and I hope it works for test too (still training so I can't run it in test yet).

https://github.com/Montyro/2DPASS

**Comment by cama36** [comment]
> Thats just how the dataloader is programmed, if you don't have the pictures downloaded, it will still search for them and return errors. I created a fork that makes the dataloader ignore the 2D information when using --baseline only. It works for training, and I hope it works for test too (still training so I can't run it in test yet).
> 
> https://github.com/Montyro/2DPASS
Thank you very much for your work, which has helped me a lot. Hope you can get a good result. Could you remind me if it works for the test too.
