### ISSUE TITLE
Some details about training and inference

### ISSUE THREAD

**Issue by PinTang1999** [yanx27/2DPASS#3]
Thank you for your exellent work. I am quite curious about the training and inference details about the MSFSKD module. As stated in the paper, the 2D learner takes the 3D features (64 channels) of points in image fov as input and output the enhanced 3D features. Hence, what is the input to the 2D learner at inference phase since the image and the 'points in image fov' is not given in the inference phase. Besides, how do the enhanced 3D features connect with the backbone feature, that is, how the features goes back to the SPVCNN encoder?

Thank you.

**Comment by yanx27** [comment]
Hi, the input for the 2D learner is not utilized in the inference phase, but it helps the optimization during the training.

**Comment by PinTang1999** [comment]
Thank you! So the lines going to/from 2D Learner in Fig.4 in the paper should be dash instaed of solid?
