### ISSUE TITLE
How to save the predicted labels?

### ISSUE THREAD

**Issue by whattotype** [yanx27/2DPASS#30]
Thanks for your great work! I'm trying to use the model to visualize the segmentation result, can you tell me how to save the predicted labels?

**Comment by yanx27** [comment]
@whattotype Hi, you can use `--submit_to_server` arg to save the prediction results, and visualize them through  semantickitti-api. If you want to save the results on validation set, you need to modify the split [test](https://github.com/yanx27/2DPASS/blob/8570d0e5209b056e5e9bc242479bbd57241589cc/config/label_mapping/semantic-kitti.yaml#L200) to 08.

**Comment by KantaphatLeelakunwet** [comment]
@yanx27 I have run using `--submit_to_server`, but may I know where is the result saved? Which folder does the results being stored? Thank you in advance!

**Comment by 199509liwen** [comment]
Have you been able to create the visual effects like those in the paper? If so, could you share the visualization code with me?
