### ISSUE TITLE
SimpleProfiler error while training

### ISSUE THREAD

**Issue by udaysankar01** [yanx27/2DPASS#33]
Hi, I would first like to be thankful for providing this repo. I have installed all the dependencies, and followed each step in local machine. However, I get stuck with the following error, both in training and testing with pre-trained weights. It would be grateful if I could get help with this. 

![Screenshot 2022-12-10 061711](https://user-images.githubusercontent.com/22807879/206852301-ea2855a4-0889-4551-8188-9df1b96ae904.png)

**Comment by DonghunP** [comment]
@udaysankar01 I think this code doesn't updated properly :(

**Comment by yanx27** [comment]
@udaysankar01 Hi, did you check using the same Lightning version?

**Comment by HamoodYA** [comment]
Hi,
I fixed it using the below:
pytorch_lightning==1.3.8 and torchmetrics==0.5

**Comment by hty1233** [comment]
@HamoodYA the version of my pytorch is 1.13.1,so l can't install the pytorch_lightning==1.3.8 and torchmetrics==0.5,how can l solve the problm?
