### ISSUE TITLE
Exporting to the onnx format and implement onnxruntime inference 

### ISSUE THREAD

**Issue by ZhouYC-X** [yanx27/2DPASS#35]
Thanks for sharing your code as well as the great work you have accomplished.
I want to know if the 2DPASS support exporting to the onnx format and implement onnxruntime inference?
Looking forward for your reply.

**Comment by yanx27** [comment]
@ZhouYC-X Hi, thanks for your attention. I have not tried to export 2DPASS into onnx, which mainly depends on whether the dependency library [spconv](https://github.com/traveller59/spconv) supports it.

**Comment by ZhouYC-X** [comment]
@yanx27  Thank you for your reply and I will try it later.

**Comment by xueyingliu** [comment]
> @yanx27 Thank you for your reply and I will try it later.

Hi, have you exported the model to onnx, I need to do the same thing.

**Comment by xueyingliu** [comment]
@ZhouYC-X Hi, have you exported the model to onnx? I need to do the same thing.

**Comment by suhansu** [comment]
> @yanx27 Thank you for your reply and I will try it later.
how about ? body
