### ISSUE TITLE
validation_epoch_end

### ISSUE THREAD

**Issue by ba77-ku** [yanx27/2DPASS#38]
It gives a size error when calculating iou, what do you think could be the problem?
![hemen](https://user-images.githubusercontent.com/68560491/211811242-dc7125fe-b161-4f71-9c3b-8e5ac645da28.png)

**Comment by yanx27** [comment]
This result might be caused by different NumPy version.

**Comment by hahahaff** [comment]
> It gives a size error when calculating iou, what do you think could be the problem? ![hemen](https://user-images.githubusercontent.com/68560491/211811242-dc7125fe-b161-4f71-9c3b-8e5ac645da28.png)

Hello, have you solved this problem? I also encountered the same problem. Looking forward to your reply.
