### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by a-krawciw** [yanx27/2DPASS#39]
Hi, thanks for publishing your code.

Is there any way to visualize the results on the validation set/save the network predictions to a file?

**Comment by yanx27** [comment]
Hi @a-krawciw You can modify the test set [here](https://github.com/yanx27/2DPASS/blob/b516779371afcc32bb1a3d6c1a0eca8473890feb/config/label_mapping/semantic-kitti.yaml#L200) to 08 and use `--submit_to_server` option. The saved results can be visualized by official SemanticKITTI toolkit.
