### ISSUE TITLE
Fails to load pretrained model

### ISSUE THREAD

**Issue by warchiba** [yanx27/2DPASS#40]
Hi!
I have problems with loading a pretrained model. It is said that  tensors shaped mismatched. 
```
Traceback (most recent call last):
  File "main.py", line 181, in <module>
    my_model = my_model.load_from_checkpoint(configs.checkpoint, config=configs, strict=(not configs.pretrain2d))
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 157, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 205, in _load_model_state
    model.load_state_dict(checkpoint['state_dict'], strict=strict)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for get_model:
        size mismatch for model_3d.spv_enc.0.v_enc.0.layers_in.0.weight: copying a param with shape torch.Size([64, 1, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 64, 64]).
        size mismatch for model_3d.spv_enc.0.v_enc.0.layers.0.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
        size mismatch for model_3d.spv_enc.0.v_enc.0.layers.3.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
        size mismatch for model_3d.spv_enc.0.v_enc.1.layers_in.0.weight: copying a param with shape torch.Size([64, 1, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 64, 64]).
        size mismatch for model_3d.spv_enc.0.v_enc.1.layers.0.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
        size mismatch for model_3d.spv_enc.0.v_enc.1.layers.3.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
        size mismatch for model_3d.spv_enc.1.v_enc.0.layers_in.0.weight: copying a param with shape torch.Size([64, 1, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 64, 64]).
        size mismatch for model_3d.spv_enc.1.v_enc.0.layers.0.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
        size mismatch for model_3d.spv_enc.1.v_enc.0.layers.3.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
        size mismatch for model_3d.spv_enc.1.v_enc.1.layers_in.0.weight: copying a param with shape torch.Size([64, 1, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 64, 64]).
        size mismatch for model_3d.spv_enc.1.v_enc.1.layers.0.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
        size mismatch for model_3d.spv_enc.1.v_enc.1.layers.3.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
        size mismatch for model_3d.spv_enc.2.v_enc.0.layers_in.0.weight: copying a param with shape torch.Size([64, 1, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 64, 64]).
        size mismatch for model_3d.spv_enc.2.v_enc.0.layers.0.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
        size mismatch for model_3d.spv_enc.2.v_enc.0.layers.3.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
        size mismatch for model_3d.spv_enc.2.v_enc.1.layers_in.0.weight: copying a param with shape torch.Size([64, 1, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 64, 64]).
        size mismatch for model_3d.spv_enc.2.v_enc.1.layers.0.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
        size mismatch for model_3d.spv_enc.2.v_enc.1.layers.3.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
        size mismatch for model_3d.spv_enc.3.v_enc.0.layers_in.0.weight: copying a param with shape torch.Size([64, 1, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 64, 64]).
        size mismatch for model_3d.spv_enc.3.v_enc.0.layers.0.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
        size mismatch for model_3d.spv_enc.3.v_enc.0.layers.3.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
        size mismatch for model_3d.spv_enc.3.v_enc.1.layers_in.0.weight: copying a param with shape torch.Size([64, 1, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 64, 64]).
        size mismatch for model_3d.spv_enc.3.v_enc.1.layers.0.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
        size mismatch for model_3d.spv_enc.3.v_enc.1.layers.3.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
```

How to solve it? Should I change config file for using your pretrained model?

**Comment by yanx27** [comment]
@warchiba Hi, did you check use the same library version with us?

**Comment by warchiba** [comment]
> @warchiba Hi, did you check use the same library version with us?

Yes
By the way, I tried different versions, none works

**Comment by yanx27** [comment]
But according to the error, it seems that you use different spconv version.

**Comment by BXYMartin** [comment]
Using spconv==1.2.1 and cumm==0.2.3 solved my problem.

**Comment by Jaywxy** [comment]
> Using spconv==1.2.1 and cumm==0.2.3 solved my problem.

@BXYMartin it may be not the problem of spconv version,I use spconv==1.2.1 get the same error

**Comment by Jaywxy** [comment]
hi,Did you solve this problem?

> Hi! I have problems with loading a pretrained model. It is said that tensors shaped mismatched.
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 181, in <module>
>     my_model = my_model.load_from_checkpoint(configs.checkpoint, config=configs, strict=(not configs.pretrain2d))
>   File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 157, in load_from_checkpoint
>     model = cls._load_model_state(checkpoint, strict=strict, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 205, in _load_model_state
>     model.load_state_dict(checkpoint['state_dict'], strict=strict)
>   File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for get_model:
>         size mismatch for model_3d.spv_enc.0.v_enc.0.layers_in.0.weight: copying a param with shape torch.Size([64, 1, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 64, 64]).
>         size mismatch for model_3d.spv_enc.0.v_enc.0.layers.0.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
>         size mismatch for model_3d.spv_enc.0.v_enc.0.layers.3.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
>         size mismatch for model_3d.spv_enc.0.v_enc.1.layers_in.0.weight: copying a param with shape torch.Size([64, 1, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 64, 64]).
>         size mismatch for model_3d.spv_enc.0.v_enc.1.layers.0.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
>         size mismatch for model_3d.spv_enc.0.v_enc.1.layers.3.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
>         size mismatch for model_3d.spv_enc.1.v_enc.0.layers_in.0.weight: copying a param with shape torch.Size([64, 1, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 64, 64]).
>         size mismatch for model_3d.spv_enc.1.v_enc.0.layers.0.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
>         size mismatch for model_3d.spv_enc.1.v_enc.0.layers.3.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
>         size mismatch for model_3d.spv_enc.1.v_enc.1.layers_in.0.weight: copying a param with shape torch.Size([64, 1, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 64, 64]).
>         size mismatch for model_3d.spv_enc.1.v_enc.1.layers.0.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
>         size mismatch for model_3d.spv_enc.1.v_enc.1.layers.3.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
>         size mismatch for model_3d.spv_enc.2.v_enc.0.layers_in.0.weight: copying a param with shape torch.Size([64, 1, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 64, 64]).
>         size mismatch for model_3d.spv_enc.2.v_enc.0.layers.0.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
>         size mismatch for model_3d.spv_enc.2.v_enc.0.layers.3.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
>         size mismatch for model_3d.spv_enc.2.v_enc.1.layers_in.0.weight: copying a param with shape torch.Size([64, 1, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 64, 64]).
>         size mismatch for model_3d.spv_enc.2.v_enc.1.layers.0.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
>         size mismatch for model_3d.spv_enc.2.v_enc.1.layers.3.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
>         size mismatch for model_3d.spv_enc.3.v_enc.0.layers_in.0.weight: copying a param with shape torch.Size([64, 1, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 64, 64]).
>         size mismatch for model_3d.spv_enc.3.v_enc.0.layers.0.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
>         size mismatch for model_3d.spv_enc.3.v_enc.0.layers.3.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
>         size mismatch for model_3d.spv_enc.3.v_enc.1.layers_in.0.weight: copying a param with shape torch.Size([64, 1, 1, 1, 64]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 64, 64]).
>         size mismatch for model_3d.spv_enc.3.v_enc.1.layers.0.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
>         size mismatch for model_3d.spv_enc.3.v_enc.1.layers.3.weight: copying a param with shape torch.Size([64, 3, 3, 3, 64]) from checkpoint, the shape in current model is torch.Size([3, 3, 3, 64, 64]).
> ```
> 
> How to solve it? Should I change config file for using your pretrained model?
