### ISSUE TITLE
about inference time

### ISSUE THREAD

**Issue by xueyingliu** [yanx27/2DPASS#42]
Thank you for your great work! When I run the testing on SemanticKitti, I got inference time 480ms(using Tesla V100 32G), In your paper, the inference time is 62ms, I just the use the model in your Google drive folder, what's the problem?
 I use the following code to print inference time:
`t1 = time.time() `
`data_dict = self.forward(data_dict) `
`t2 = time.time() `
`print('inference time: ', t2-t1)`

**Comment by yanx27** [comment]
Hi @xueyingliu The inference time in our paper is gained by the pure time for the network inference. You can follow the below setting to test the speed. Note that keep `--num_vote` is 1 during the inference:
```
torch.cuda.synchronize()
start = time.time()
model(data_dict)
torch.cuda.synchronize()
end = time.time()
print("inference time:", end - start )
```

**Comment by xueyingliu** [comment]
@yanx27 Got it, Thank you so much for your reply.
