### ISSUE TITLE
details about SPVCNN

### ISSUE THREAD

**Issue by inspirelt** [yanx27/2DPASS#5]
Hi, @yanx27 , thanks for providing the excellent work. I wonder what network configs you take in the experiments. As mentioned, you take a modified SPVCNN with resolution=0.1 and hidden dimension=64. Do they mean you change the https://github.com/mit-han-lab/spvnas/blob/69750e900d8687ac9fcc8e042b171cd1f6beffa1/core/models/semantic_kitti/spvcnn.py#L87 of cs = [32, 32, 64, 128, 256, 256, 128, 96, 96] into cs = [64, 64, 64, 64, 64, 64, 64, 64, 64] and https://github.com/mit-han-lab/spvnas/blob/69750e900d8687ac9fcc8e042b171cd1f6beffa1/configs/semantic_kitti/default.yaml#L14 of "voxel_size: 0.05" into "voxel_size: 0.1"? 

And are there any other changes to reproduce the reported results?

Thanks again.

**Comment by yanx27** [comment]
Hi @inspirelt , as described in the Sec.3.2, we did not use the U-Net architecture as SPVCNN, but directly concatenate point-wise features from each encoder layer to gain the prediction.  By the way, our codebase is not based upon [torchsparse](https://github.com/mit-han-lab/spvnas/blob/69750e900d8687ac9fcc8e042b171cd1f6beffa1/core/models/semantic_kitti/spvcnn.py#L87) but on [spconv2](https://github.com/traveller59/spconv). Therefore, the speed may be slightly different.
