### ISSUE TITLE
How is seg_labelweights computed?

### ISSUE THREAD

**Issue by timmynth** [yanx27/2DPASS#51]
How did you compute the seg_labelweights?

I try to make some reasons out of it. But it makes no sense to me.

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/8543247/229983501-4502493c-e742-4b4a-880b-db1833d2ba4d.png">

**Comment by timmynth** [comment]
I think I misunderstand. It's the number of points for each class instead of loss weights?

**Comment by brahami14** [comment]
By using the  code extract from https://github.com/PRBonn/semantic-kitti-api/blob/master/content.py
