### ISSUE TITLE
two classes have not been trained on SemanticKitti

### ISSUE THREAD

**Issue by potaosking** [yanx27/2DPASS#54]
![image](https://user-images.githubusercontent.com/52370572/231093927-5418578a-dea0-43ea-b35e-3d47ccb12a04.png)
Hello,Thank you for your great work!When I train on SemanticKitti,the motorcyclist and other-ground classes  get very low score,

**Comment by brahami14** [comment]
![image](https://user-images.githubusercontent.com/103207573/231179065-2ea98edd-c100-49d8-9318-51bc9d875797.png)
i have the same issue

**Comment by Montyro** [comment]
The validation sequence of semantic-kitti has only 5 points labeled as motorcyclist, therefore it cannot distinguish them as a motorcyclist, obtaining a 0% IoU score. The same issue happens with the other-ground class.

If you run in on test and upload results to the benchmark server, you will see it indeed learns those classes.

**Comment by potaosking** [comment]
> The validation sequence of semantic-kitti has only 5 points labeled as motorcyclist, therefore it cannot distinguish them as a motorcyclist, obtaining a 0% IoU score. The same issue happens with the other-ground class.
> 
> If you run in on test and upload results to the benchmark server, you will see it indeed learns those classes.

thanks
