### ISSUE TITLE
Dataset Nuscenes

### ISSUE THREAD

**Issue by brahami14** [yanx27/2DPASS#64]
Hello, 

for the Nuscenes dataset which we need to load, is this the one ?? because i didn't find file attribute.py
![image](https://github.com/yanx27/2DPASS/assets/103207573/39cdd6ed-8e36-4c6e-b4ba-513e8df8ce2a)

**Comment by brahami14** [comment]
i have another question please what is the value of splits in the function class nuScenes, i got error: that this variable is not defined before: 
Thanks in advance 

@register_dataset
class nuScenes(data.Dataset):
    def __init__(self, config, data_path, imageset='train', num_vote=1):
       
        if config.debug:
            version = 'v1.0-mini'
            scenes = splits.mini_train
        else:
            if imageset != 'test':
                version = 'v1.0-trainval'
                if imageset == 'train':
                    scenes = splits.train
                else:
                    
                    scenes = splits.val
                    
            else:
                version = 'v1.0-test'
                scenes = splits.test

**Comment by rsleishaui** [comment]
> 你好，
> 
> 对于我们需要加载的 Nuscenes 数据集，是这个吗？因为我没有找到文件 attribute.py ![图像](https://private-user-images.githubusercontent.com/103207573/244085107-39cdd6ed-8e36-4c6e-b4ba-513e8df8ce2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzQwNzEsIm5iZiI6MTcyOTIzMzc3MSwicGF0aCI6Ii8xMDMyMDc1NzMvMjQ0MDg1MTA3LTM5Y2RkNmVkLThlMzYtNGM2ZS1iNGJhLTUxM2U4ZGY4Y2UyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwNjQyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTVkMzVjZjUxM2VhOGFmMjZhZmE1N2RhZTgwZTkyODBjNDJlODhhNGUwOWNjZGE3N2QzMzk0MTc1ODllNjkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jfmOcZqaMeaFjchqLSGph2OhsSvEfWB1pOALSUxPghc)
Did you solve it?

**Comment by rsleishaui** [comment]
Did you solve it?
