### ISSUE TITLE
about pretrained model

### ISSUE THREAD

**Issue by Jaywxy** [yanx27/2DPASS#68]
I downloaded the pretrained model "2DPASS_6scale_256dim",and ran command `python main.py --config config/2DPASS-large-semantickitti.yaml --gpu 0 --test --num_vote 1 --checkpoint ./pretrained_model/2DPASS_6scale_256dim/best_model.ckpt` 
got error 
`RuntimeError: Error(s) in loading state_dict for get_model:
        size mismatch for model_3d.spv_enc.0.v_enc.0.layers_in.0.weight: copying a param with shape torch.Size([256, 1, 1, 1, 256]) from checkpoint, the shape in current model is torch.Size([1, 1, 1, 256, 256]).`
 why the param shape error? I amnot change the model

**Comment by Jaywxy** [comment]
ran command python main.py --config ./pretrained_model/2DPASS_6scale_256dim/2DPASS-large-semantickitti.yaml --gpu 0 --test --num_vote 1 --checkpoint ./pretrained_model/2DPASS_6scale_256dim/best_model.ckpt
still error

**Comment by Jaywxy** [comment]
pretrained model `2DPASS_4scale_64dim` 
the same error

**Comment by Jaywxy** [comment]
重新配置环境解决问题

**Comment by Ling53** [comment]
兄弟能分享一下你的环境吗
