### ISSUE TITLE
Training Details

### ISSUE THREAD

**Issue by fengjiang5** [yanx27/2DPASS#7]
Hello, Congratulation for your paper and it is a very good job. I didn't find which GPUs you use for training and inference, So could you please give me a suggestion about that?

**Comment by yanx27** [comment]
Hi @fengjiang5 , our experimental results are gained by a single Nvidia Tesla V100 GPU. But our codebase will support DDP multi-GPU training, and one can reproduce the results through other GPUs such as 2080.
