### ISSUE TITLE
Size mismatch for pretrained model

### ISSUE THREAD

**Issue by fu-7** [yanx27/2DPASS#77]
I test with the pretrained model by your test code but got `RuntimeError: Error(s) in loading state_dict for get_model:
        size mismatch for model_3d.spv_enc.0.v_enc.0.layers_in.0.weight: copying a param with shape ('model_3d.spv_enc.0.v_enc.0.layers_in.0.weight', torch.Size([64, 64, 1, 1, 1])) from checkpoint,the shape in current model is torch.Size([64, 1, 1, 1, 64]).
        size mismatch for model_3d.spv_enc.0.v_enc.0.layers.0.weight: copying a param with shape ('model_3d.spv_enc.0.v_enc.0.layers.0.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for model_3d.spv_enc.0.v_enc.0.layers.3.weight: copying a param with shape ('model_3d.spv_enc.0.v_enc.0.layers.3.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for model_3d.spv_enc.0.v_enc.1.layers_in.0.weight: copying a param with shape ('model_3d.spv_enc.0.v_enc.1.layers_in.0.weight', torch.Size([64, 64, 1, 1, 1])) from checkpoint,the shape in current model is torch.Size([64, 1, 1, 1, 64]).
        size mismatch for model_3d.spv_enc.0.v_enc.1.layers.0.weight: copying a param with shape ('model_3d.spv_enc.0.v_enc.1.layers.0.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for model_3d.spv_enc.0.v_enc.1.layers.3.weight: copying a param with shape ('model_3d.spv_enc.0.v_enc.1.layers.3.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for model_3d.spv_enc.1.v_enc.0.layers_in.0.weight: copying a param with shape ('model_3d.spv_enc.1.v_enc.0.layers_in.0.weight', torch.Size([64, 64, 1, 1, 1])) from checkpoint,the shape in current model is torch.Size([64, 1, 1, 1, 64]).
        size mismatch for model_3d.spv_enc.1.v_enc.0.layers.0.weight: copying a param with shape ('model_3d.spv_enc.1.v_enc.0.layers.0.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for model_3d.spv_enc.1.v_enc.0.layers.3.weight: copying a param with shape ('model_3d.spv_enc.1.v_enc.0.layers.3.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for model_3d.spv_enc.1.v_enc.1.layers_in.0.weight: copying a param with shape ('model_3d.spv_enc.1.v_enc.1.layers_in.0.weight', torch.Size([64, 64, 1, 1, 1])) from checkpoint,the shape in current model is torch.Size([64, 1, 1, 1, 64]).
        size mismatch for model_3d.spv_enc.1.v_enc.1.layers.0.weight: copying a param with shape ('model_3d.spv_enc.1.v_enc.1.layers.0.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for model_3d.spv_enc.1.v_enc.1.layers.3.weight: copying a param with shape ('model_3d.spv_enc.1.v_enc.1.layers.3.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for model_3d.spv_enc.2.v_enc.0.layers_in.0.weight: copying a param with shape ('model_3d.spv_enc.2.v_enc.0.layers_in.0.weight', torch.Size([64, 64, 1, 1, 1])) from checkpoint,the shape in current model is torch.Size([64, 1, 1, 1, 64]).
        size mismatch for model_3d.spv_enc.2.v_enc.0.layers.0.weight: copying a param with shape ('model_3d.spv_enc.2.v_enc.0.layers.0.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for model_3d.spv_enc.2.v_enc.0.layers.3.weight: copying a param with shape ('model_3d.spv_enc.2.v_enc.0.layers.3.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for model_3d.spv_enc.2.v_enc.1.layers_in.0.weight: copying a param with shape ('model_3d.spv_enc.2.v_enc.1.layers_in.0.weight', torch.Size([64, 64, 1, 1, 1])) from checkpoint,the shape in current model is torch.Size([64, 1, 1, 1, 64]).
        size mismatch for model_3d.spv_enc.2.v_enc.1.layers.0.weight: copying a param with shape ('model_3d.spv_enc.2.v_enc.1.layers.0.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for model_3d.spv_enc.2.v_enc.1.layers.3.weight: copying a param with shape ('model_3d.spv_enc.2.v_enc.1.layers.3.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for model_3d.spv_enc.3.v_enc.0.layers_in.0.weight: copying a param with shape ('model_3d.spv_enc.3.v_enc.0.layers_in.0.weight', torch.Size([64, 64, 1, 1, 1])) from checkpoint,the shape in current model is torch.Size([64, 1, 1, 1, 64]).
        size mismatch for model_3d.spv_enc.3.v_enc.0.layers.0.weight: copying a param with shape ('model_3d.spv_enc.3.v_enc.0.layers.0.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for model_3d.spv_enc.3.v_enc.0.layers.3.weight: copying a param with shape ('model_3d.spv_enc.3.v_enc.0.layers.3.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for model_3d.spv_enc.3.v_enc.1.layers_in.0.weight: copying a param with shape ('model_3d.spv_enc.3.v_enc.1.layers_in.0.weight', torch.Size([64, 64, 1, 1, 1])) from checkpoint,the shape in current model is torch.Size([64, 1, 1, 1, 64]).
        size mismatch for model_3d.spv_enc.3.v_enc.1.layers.0.weight: copying a param with shape ('model_3d.spv_enc.3.v_enc.1.layers.0.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for model_3d.spv_enc.3.v_enc.1.layers.3.weight: copying a param with shape ('model_3d.spv_enc.3.v_enc.1.layers.3.weight', torch.Size([64, 64, 3, 3, 3])) from checkpoint,the shape in current model is torch.Size([64, 3, 3, 3, 64]). `

**Comment by Ikhyeon-Cho** [comment]
Can you share your experience to resolve this error?
