### ISSUE TITLE
Some question in your paper

### ISSUE THREAD

**Issue by JJBUP** [yanx27/2DPASS#8]
First of all, congratulations on your achievements！
I would like to ask some question in your paper

in fig 3(a), I understand that the point P ^ of the image path can be mapped from P, and the red line indicates that correspondence operation can obtain the points in the corresponding camera image.

But I don't know what the meaning of the blue box I draw in the figure is. What is the relationship between p ^ and M img?
![fig 3](https://user-images.githubusercontent.com/55440381/190960643-8b43c698-01d9-441f-838f-71b4895a3b37.png)

**Comment by JJBUP** [comment]
First of all, congratulations on your achievements！
I would like to ask some question in your paper

in fig 3(a), I understand that the point P ^ of the image path can be mapped from P, and the red line indicates that correspondence operation can obtain the points in the corresponding camera image. 

But I don't know what the meaning of the blue lines I draw in the figure is. What is the relationship between p ^ and M img?

![fig 3](https://user-images.githubusercontent.com/55440381/190960405-8c7a2785-9114-41d4-808b-faead4a63981.png)

**Comment by yanx27** [comment]
Hi @JJBUP ， since the codes have already released, you can check it in the code.
